version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: kanaerudo/graphql-calculator-altair:latest
    container_name: calculator-api
    ports:
      - "5000:80"       # HostPort:ContainerPort
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped