services:
  calculator-api:
    image: kanaerudo/graphql-calculator-altair:latest
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080;https://0.0.0.0:8081
    restart: unless-stopped